### ISSUE TITLE
Bcc.exe cannot cast from short * to unsigned short *

### ISSUE THREAD

**Issue by ThomasMertes** [sal55/langs#2]
The following test program:
------------------------- Begin of tst298.c -------------------------
#include "stdio.h"

typedef unsigned short *wstriType;

int main (int argc, char *argv[])
{
  wchar_t *stri_buffer;
  wstriType wide_string;

  stri_buffer = wide_string;
  return 0;
}
------------------------- End of tst298.c -------------------------
Triggers this error:
Z:\home\tm\seed7_5\src>..\bin\bcc tst298.c
Compiling tst298.c to tst298.exe
ref ushort
ref short
In function main
Type error: Can't do conversion ref => ref on line 10 tst298.c

**Comment by sal55** [comment]
I've fixed the problems reported; see www.bcas.freeuk.com/bcc.exe

But, trying to compile further modules, I'm stuck on WDIR in version.h:

#define os_DIR WDIR

Edited:

(I'd been replying to these on gmail, didn't know I could do it on github, or that I could edit!)

I've found out where WDIR is defined, which is when version.h has OS_STRI_WCHAR, then it is defined somewhere in Seed7. Presumably bcc passes some test, but probably inappropriately since it then seems to mix up normal and wide char types, such as in infile.c line 202: the call to os_fopen, where the mismatch is between signed char* and unsigned short* (the type of wchar).

OS_STRI_CHAR gets sets because a test involving FindNextFileW succeeds, but I'm rather lost with it now right now.

**Comment by ThomasMertes** [comment]
Hi Bart,
 
thank you for providing a new bcc.exe. I tried it with the makefile mk_bcc.mak
(see attachment) and almost everything (except drw_win.c) compiles.
Unfortunately the definition of CreateBitmap (defined in wingdi.h / windows.h)
is still missing. Please add this definition to your bcc.exe includes:
 
HBITMAP CreateBitmap(int,int,UINT,UINT,const VOID *);
 
I suggest to use make and mk_bcc.mak to compile Seed7 with bcc.

Just copy mk_bcc.mak to the seed7/src directory. Then it can can be used
(in the seed7/src directory) with:
 
make -f mk_bcc.mak clean

make -f mk_bcc.mak depend
make -f mk_bcc.mak
 
If your make program has problems you can use mingw32-make or make7
(see: https://sourceforge.net/projects/seed7/files/bin/make7.exe/download ).
Make7 is a make utility that has many built in commands. This way it does
not depend on the correct installation of a shell and other tools.
 
The makefile mk_bcc.mak uses gcc to link the final program and ar is used
to create libraries.
 
The Seed7 compiler assumes that compiling and linking is done by the same
tool. As bcc seems not be able to link .obj and .a files to an .exe compilation
with s7c is currently not possible.
 
Regarding the missing definition of WDIR. WDIR is defined in dir_win.h.
But dir_win.h is not always included. I saw that you used
 
make depend
 
In this case the name of the makefile is makefile and this contains a slightly
different list of source files and some definitions that fit to Linux. OTOH
mk_bcc.mak is a makefile with the source file list for windows and definitions
that fit to Windows and bcc.
 
Thank you again for your help.
 
Regards Thomas

**Comment by ThomasMertes** [comment]
WDIR is defined in dir_win.h. If Seed7 is compiled with the right makefile (mk_bcc.mak)
the definition of WDIR in dir.win.h is activated (assuming that you use windows).

I sent mk_bcc.mak by email. I came quite far with it. Just drw_win.c cannot be compiled,
because the definition of CreateBitmap is missing (see my comment regarding missing
definitions in wingdi.h):

HBITMAP CreateBitmap(int,int,UINT,UINT,const VOID *);
